### ISSUE TITLE
the supplementary reads is included in the results

### ISSUE THREAD

**Issue by WellJoea** [wdecoster/nanostat#31]
The result is included supplementary reads When  I used NanoStat to state the bam file.
So the bam file need to be filter by  the command "samtools view -F 256 -F 272 -F 2048 -F 2064", then the result will get the right   number of reads. 
So, is there a  way to use the pipe operator as the standard input? Such as "samtools view -F 256 | NanoStat --bam stdin bamfile > out.txt "

**Comment by wdecoster** [comment]
The result does indeed by default include supplementary alignments because they are real. However, a while ago I made changes to NanoPlot to exclude supplementary reads for another request. 

I have now ported these changes to NanoStat, and in v1.5 you have a --no_supplementary option. That version is now available through pip.

**Comment by WellJoea** [comment]
Thank you very much!
Yes! the supplementary alignments should bed included in the result, especially computing the total aligned bases.
But, when to get the reads statistics,such as mean reads lengh, number of reads, the supplementary reads maybe have an effect on the result.

**Comment by wdecoster** [comment]
Yes, so it's good to have it as an option I guess. Please let me know if you have other suggestion, feedback or questions.
